name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    #  kill cache (prevents Gradle 9 issue)
    - name: Clean Gradle cache
      run: rm -rf ~/.gradle

    #  ensure wrapper is executable
    - name: Grant permission
      run: chmod +x gradlew

    #  FORCE correct Gradle version
    - name: Force Gradle 7.6
      run: ./gradlew wrapper --gradle-version 7.6

    #  build
    - name: Build APK
      run: ./gradlew assembleDebug --no-daemon

    #  upload
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk